name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-actions@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          project: router448461-github-io
